' Update dari fajar

@startuml ERD Database PT EMJE PANDAJAYA

skinparam linetype ortho

'=================================
' Enums
'=================================

' Table     
' enum users.role
enum Role{
    +ADMIN
    +PESERTA
    +BENDAHARA
    +PENGELOLA_PENDAFTARAN
}

' Table profile_user
' enum profil_user.pendidikan_terakhir
enum PendidikanTerakhir{
    +D3/S1
    +SMK/SMA
    +SMP
    +SD
}
' enum profil_user.jenis_kelamin
enum JenisKelamin{
    +Pria
    +Wanita
}

' Table pelatihan
' enum pelatihan.kategori
enum KategoriPelatihan{
    +manufaktur
    +pengolahan_makanan
    +pertanian
    +konstruksi
    +kaigo
    +logistik
    +metal
}
' enum pelatihan.status
enum StatusPelatihan{
    +AKTIF
    +NONAKTIF
}

' Table ujian_pelatihan
' ujian_pelatihan.status
enum StatusJadwalUjianPelatihan{
    +TERJADWAL
    +BERLANGSUNG
    +SELESAI
}
' Table hasil_ujian_pelatihan
' enum hasil_ujian_pelatihan.status
enum StatusHasilUjianPelatihan{
    +LULUS
    +TIDAK_LULUS
    +REMEDIAL
}

' Table kontrak_Kerja
' enum kontrak_kerja.status
enum StatusKontrakKerja{
    +AKTIF
    +NONAKTIF
}

' Table pelatihan_diikuti
' enum pelatihan_diikuti.status
enum StatusPelatihanDiikuti{
    +BERLANGSUNG
    +SELESAI
    +DIBATALKAN
}
' Table kontrak_kerja_diikuti
' enum kontrak_kerja_diikuti.status
enum StatusKontrakKerjaDiikuti{
    +BERLANGSUNG
    +SELESAI
    +DIBATALKAN
}
' Table pengajuan_kontrak_kerja
' enum pengajuan_kontrak_kerja.status
enum StatusPengajuanKontrakKerja{
    +DISETUJUI
    +DITOLAK
    +DALAM_PROSES
    +DIBATALKAN
}
' Table pendaftaran_pelatihan
' enum pendaftaran_pelatihan.status
enum StatusPendaftaranPelatihan{
    +DITERIMA
    +DITOLAK
    +DALAM_PROSES
    +DIBATALKAN
}
' Table cicilan_biaya_pelatihan
' enum cicilan_biaya_pelatihan.status
enum StatusCicilanPelatihan{
    +DIBAYAR
    +BELUM_BAYAR
    +DIBATALKAN
}

' Table transaksi_rekening
' enum transaksi_rekening.status
enum TipeTransaksi {
    +Pemasukan
    +Pengeluaran
}
' Table cicilan_biaya_pelatihan
enum TenorCicilanPelatihan{
    +TIGA_BULAN
    +ENAM_BULAN
    +SEMBILAN_BULAN
    +DUA_BELAS_BULAN
}
' Table pendaftaran_pelatihan
' enum pendaftaran_pelatihan.metode_pembayaran
enum SkemaPembayaranPendaftaranPelatihan{
    +CASH
    +CICILAN
}
' Table pembayaran_pendaftaran
' enum pembayaran_pendaftaran.status
enum StatusPembayaran{
    +DITERIMA
    +DITOLAK
}
' Table pembayaran_pendaftaran
' enum pembayaran_pendaftaran.metode_pembayaran
enum JenisPembayaran{
    +ANGSURAN
    +PELUNASAN
    +DP
}
'  Table gelombang_pelatihan
' enum gelombang_pelatihan.sesi
enum SesiGelombangPelatihan{
    +PENDAFTARAN
    +BERLANGSUNG
    +SELESAI
}



'==================================
' Tables
'==================================

' Users flow
entity users{
    *id : Bigint
    ===
    -name : String
    -email : String
    -password : String
    -role : Role
}

entity profil_user{
    *id : Bigint
    -users_id : Bigint
    ===
    -nama_lengkap : String
    -alamat : String
    -nomor_telepon : String
    -pendidikan_terakhir : PendidikanTerakhir
    -jenis_kelamin : JenisKelamin
    -tanggal_lahir : Date
    -foto_profil : String
    -ktp : String
    -ijazah : String
}

' Pelatihan Flow
entity pelatihan{
    *id : Bigint
    ===
    -nama_pelatihan : String
    -nominal_biaya : Decimal (15,2)
    -persentasi_dp : Decimal (5,2)
    -durasi_pelatihan : Int
    -kategori_pelatihan : String
    -deskripsi : String
    -status : StatusPelatihan
}
entity pendaftaran_pelatihan{
    *id : Bigint
    -users_id: Bigint
    -pelatihan_id: Bigint
    ===
    -status : StatusPendaftaranPelatihan
    -skema_pembayaran : SkemaPembayaranPendaftaranPelatihan
    -tenor : TenorCicilanPelatihan
    -catatan : Text
}
entity pembayaran_pelatihan{
    *id : Bigint
    -pendaftaran_pelatihan_id : Bigint
    ===
    -nominal : Decimal (15,2)
    -status : StatusPembayaran
    -jenis_pembayaran : JenisPembayaran
    -bukti_pembayaran : String
    -catatan : Text
    -tanggal_bayar : Datetime
}
entity pelatihan_diikuti{
    *id : Bigint
    -pendaftaran_pelatihan_id : Bigint
    -gelombang_pelatihan_id : Bigint
    ===
    -status : StatusPelatihanDiikuti
}
entity gelombang_pelatihan{
    *id : Bigint
    -pelatihan_id : Bigint
    ---
    -tanggal_mulai : Datetime
    -tanggal_selesai : Datetime
    -sesi : SesiGelombangPelatihan
    -maksimal_peserta : Int
}
entity jadwal_ujian_pelatihan{
    *id : Bigint
    -gelombang_pelatihan_id : Bigint
    ===
    -nama_ujian : String
    -lokasi : String
    -tanggal_mulai : Datetime
    -tanggal_selesai : Datetime
    -status : StatusJadwalUjianPelatihan
}
entity hasil_ujian_pelatihan{
    *id : Bigint
    -jadwal_ujian_pelatihan_id : Bigint
    ===
    -nilai : decimal(5,2)
    -status : StatusHasilUjianPelatihan
}
entity sertifikasi{
    *id : Bigint
    -pelatihan_diikuti_id : Bigint
    ===
    nomor_sertifikat : String
    tanggal_terbit : Datetime
}

' Kontrak kerja flow
entity pengajuan_kontrak_kerja{
    *id : Bigint
    -users_id : Bigint
    -kontrak_kerja_id : Bigint
    ===
    -surat_lamaran : String
    -status : StatusPengajuanKontrakKerja
}

entity kontrak_kerja{
    *id : Bigint
    ===
    -nama_perusahaan : String
    -gaji_terendah : Decimal (15,2)
    -gaji_tertinggi : Decimal (15,2)
    -deskripsi : Text
    -status : StatusKontrakKerja
    -durasi_kontrak_keja : Int
}

entity kontrak_kerja_diikuti{
    *id : Bigint
    -pengajuan_kontrak_kerja_id : Bigint
    ===
    -status : StatusKontrakKerjaDiikuti
}

' Rekening flow
entity rekening {
    *id : Bigint
    ===
    -name : String
    -saldo : Decimal (15,2)
}

entity transaksi_rekening{
    *id : Bigint
    ===
    -nominal_transaksi : Decimal (15,2)
    -keterangan : Text
    -tipe_transaksi : TipeTransaksi
    -rekening_id : Bigint
}

' =============
' Relationship
' =============

' Flow relation profil_user
users ||--o{ profil_user

' Flow relation pelatihan
users ||--o{ pendaftaran_pelatihan
pendaftaran_pelatihan ||--|| pelatihan_diikuti
pelatihan ||--o{ pendaftaran_pelatihan
pelatihan ||--o{ gelombang_pelatihan
pendaftaran_pelatihan ||--|| pembayaran_pelatihan
gelombang_pelatihan ||--o{ pelatihan_diikuti
pelatihan_diikuti ||--|| sertifikasi
gelombang_pelatihan ||--o{ jadwal_ujian_pelatihan
jadwal_ujian_pelatihan ||--o{ hasil_ujian_pelatihan

' Flow relation kontrak_kerja
users ||--o{ pengajuan_kontrak_kerja
kontrak_kerja ||--o{ pengajuan_kontrak_kerja
pengajuan_kontrak_kerja ||--|| kontrak_kerja_diikuti

' Flow rekening
rekening ||--o{ transaksi_rekening

@enduml